apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
  labels:
    app: appointments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: sohaib2410/appointments-service:v1
          ports:
            - containerPort: 7070
          env:
            - name: SERVICE_URL
              value: "http://appointments-service:7070"
          resources:
            requests:
              memory: "64Mi"   # Requested memory
              cpu: "250m"      # Requested CPU
            limits:
              memory: "128Mi"  # Maximum memory limit
              cpu: "500m"      # Maximum CPU limit
          readinessProbe:
            httpGet:
              path: /healthz    # Endpoint to check for readiness
              port: 7070        # Port to check
            initialDelaySeconds: 5  # Delay before first check
            periodSeconds: 10        # Check every 10 seconds
          livenessProbe:
            httpGet:
              path: /healthz    # Endpoint to check for liveness
              port: 7070        # Port to check
            initialDelaySeconds: 15 # Delay before first check
            periodSeconds: 20       # Check every 20 seconds
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
