apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
  labels:
    app: appointments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: sohaib2410/appointments-service:v1
          ports:
            - containerPort: 7070
          env:
            - name: SERVICE_URL
              value: "http://appointments-service:7070"
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
