apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sohaib2410/frontend-service:v1
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_URL
              value: "http://frontend-service:3000"
          resources:
            requests:
              memory: "64Mi"   # Requested memory
              cpu: "250m"      # Requested CPU
            limits:
              memory: "128Mi"  # Maximum memory limit
              cpu: "500m"      # Maximum CPU limit
          readinessProbe:
            httpGet:
              path: /healthz    # Endpoint to check for readiness
              port: 3000        # Port to check
            initialDelaySeconds: 5  # Delay before first check
            periodSeconds: 10        # Check every 10 seconds
          livenessProbe:
            httpGet:
              path: /healthz    # Endpoint to check for liveness
              port: 3000        # Port to check
            initialDelaySeconds: 15 # Delay before first check
            periodSeconds: 20       # Check every 20 seconds
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
