apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
  labels:
    app: doctors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: sohaib2410/doctors-service:v1
          ports:
            - containerPort: 9090
          env:
            - name: SERVICE_URL
              value: "http://doctors-service:9090"
          resources:
            requests:
              memory: "64Mi"   # Requested memory
              cpu: "250m"      # Requested CPU
            limits:
              memory: "128Mi"  # Maximum memory limit
              cpu: "500m"      # Maximum CPU limit
          readinessProbe:
            httpGet:
              path: /healthz    # Endpoint to check for readiness
              port: 9090        # Port to check
            initialDelaySeconds: 5  # Delay before first check
            periodSeconds: 10        # Check every 10 seconds
          livenessProbe:
            httpGet:
              path: /healthz    # Endpoint to check for liveness
              port: 9090        # Port to check
            initialDelaySeconds: 15 # Delay before first check
            periodSeconds: 20       # Check every 20 seconds
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
