name: Appointments CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'appointments/**'
  pull_request:
    branches:
      - main
    paths:
      - 'appointments/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build and push Docker image
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t sohaib2410/appointments-service:${{ github.sha }} ./appointments
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push sohaib2410/appointments-service:${{ github.sha }}