name: Appointments CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'appointments/**'
  pull_request:
    branches:
      - main
    paths:
      - 'appointments/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build and push Docker image
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t sohaib2410/appointments-service:${{ github.sha }} ./appointments
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push sohaib2410/appointments-service:${{ github.sha }}

      # Update Image Tag in docker-compose
      - name: Update Compose Image Tag
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          chmod +x scripts/update-compose-appointments.sh
          scripts/update-compose-appointments.sh  

          


      # Commit and Push changes to GitHub (docker-compose.yml)
#      - name: Commit and Push Compose Changes
 #       run: |
  #        git config --local user.email "actions@github.com"
   #       git config --local user.name "GitHub Actions"
    #      git add ./docker-compose.yml
     #     git commit -m "Appointments CI/CD: Update docker-compose.yml with new image tag"
      #    git push origin main
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
