name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build and push Docker image
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t sohaib2410/frontend-service:${{ github.sha }} ./frontend
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push sohaib2410/frontend-service:${{ github.sha }}

      - name: Update Compose Image Tag
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          chmod +x ../../scripts/update-compose-frontend.sh  
          ../../scripts/update-compose-frontend.sh